### PR TITLE
Reuse code to compute total kmer count.

### PR DESCRIPTION
**Pull request by bagashe**
It threw me for a loop every time I saw it. So abstracting it away in an inline method next to the doc-block comment that explains the math.

### CODE REVIEW

**Comment by paoloczi** [comment]
This is a good thing to do, of course. However it seems to me that this function would belong better in a static member function of template class `ShortBaseSequence`, because it returns the number of distinct `Kmer`'s of `k` bases, and `Kmer` is a `ShortBaseSequence`.

Also I would prefer if the return type was `uint64_t` instead of `size_t`. I am trying to move away from `size_t` because it has different sizes on Linux and MacOS, which sometimes causes conversion pain and compilation problems on MacOS.

Also for the future please avoid acronyms like DRY in submit messages. Other things that I prefer avoided in submit messages are contractions, abbreviations, and emoticons. Each of these things may have an obvious meaning to the submitter but not necessarily to the reader.

**Comment by bagashe** [comment]
All good points. I need to be more mindful about using acronyms and assuming everyone knows what they mean :)

**Comment by bagashe** [comment]
@paoloczi : I moved the method to Kmer.hpp/cpp. Moving it to ShortBaseSequence seemed weird since Kmer is a specific instantiation of it. Does this seem reasonable?

**Comment by paoloczi** [comment]
As I suggested above, this function would belong better in a static member function of template class `ShortBaseSequence`, because it returns the number of distinct `Kmer`'s of `k` bases, and `Kmer` is a `ShortBaseSequence`. That would be more natural than creating a new namespace just for this purpose.

**Pull request closed without merging**
